"""Regenerate docs/RULES.md from the rule registry.

The reference is generated rather than written so it cannot drift from the
rules that actually run.  A stale security rule reference is worse than none:
people make decisions from it.

    python scripts/gen_rules_doc.py [--check]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from bulwark.core.frameworks import title_for  # noqa: E402
from bulwark.rules import REGISTRY  # noqa: E402

TARGET = ROOT / "docs" / "RULES.md"

CATEGORY_BLURB = {
    "injection": (
        "Text that reaches the model. These rules ask one question of a tool "
        "description: is it describing a capability, or issuing an instruction?"
    ),
    "composite": (
        "Combinations. Each component is individually reasonable; the exposure "
        "exists only in how they fit together."
    ),
    "supply-chain": (
        "Where a server's code comes from, and whether anyone reviewed it "
        "before it ran with the developer's privileges."
    ),
    "drift": (
        "The present compared against a pinned past. The only way to detect a "
        "change made after approval."
    ),
    "permissions": "What the agent may do without asking a human first.",
    "hooks": (
        "Shell commands the host runs automatically on agent events -- the "
        "highest-privilege extension point in the stack."
    ),
    "secrets": "Credentials written into configuration that gets committed.",
}


def render() -> str:
    lines = [
        "# Rule reference",
        "",
        "Generated by `scripts/gen_rules_doc.py` from the rule registry.",
        "Do not edit by hand.",
        "",
        "`bulwark explain <id>` prints any of these from the command line.",
        "",
        "## Index",
        "",
        "| Rule | Severity | Category | Title |",
        "|---|---|---|---|",
    ]
    for rule in REGISTRY:
        info = rule.describe()
        lines.append(
            "| [`%s`](#%s) | %s | %s | %s |"
            % (
                info["id"],
                info["id"].lower(),
                info["severity"],
                info["category"],
                info["title"],
            )
        )

    current = ""
    for rule in REGISTRY:
        info = rule.describe()
        if info["category"] != current:
            current = info["category"]
            lines.extend(
                ["", "---", "", "## " + current, "", CATEGORY_BLURB.get(current, ""), ""]
            )

        lines.extend(
            [
                "### %s" % info["id"],
                "",
                "**%s**" % info["title"],
                "",
                "`severity: %s`  `confidence: %s`%s"
                % (
                    info["severity"],
                    info["confidence"],
                    "  `requires --online`" if info["requires_online"] else "",
                ),
                "",
                info["description"],
                "",
                "**How to fix.** " + info["remediation"],
                "",
            ]
        )

        mapped = [
            "`%s %s` %s" % (framework, i, title_for(i))
            for framework, ids in sorted(info["frameworks"].items())
            for i in ids
        ]
        if mapped:
            lines.extend(["**Maps to.** " + ", ".join(mapped), ""])
        if info["references"]:
            lines.extend(
                ["**References.** " + ", ".join(info["references"]), ""]
            )

    lines.extend(
        [
            "---",
            "",
            "## Writing your own",
            "",
            "A rule is a class with metadata and one method. Point a policy at "
            "the file and it joins the same pipeline, the same reports and the "
            "same exit codes:",
            "",
            "```python",
            "from bulwark.core.models import ArtifactKind, Evidence, Severity",
            "from bulwark.core.rulebase import Rule, register",
            "",
            "",
            "@register",
            "class BannedVendor(Rule):",
            '    id = "ACME-001"',
            '    title = "Server comes from a vendor we do not permit"',
            "    severity = Severity.HIGH",
            '    category = "policy"',
            '    description = "..."',
            '    remediation = "Remove the server and use the approved one."',
            '    frameworks = {"CWE": ["CWE-829"]}',
            "",
            "    def check(self, ctx):",
            "        for server in ctx.of_kind(ArtifactKind.MCP_SERVER):",
            '            command = str(server.data.get("command", ""))',
            '            if "bannedvendor" in command:',
            "                yield self.finding(",
            "                    server,",
            '                    evidence=[Evidence(label="command", value=command)],',
            "                )",
            "```",
            "",
            "```yaml",
            "# bulwark.policy.yaml",
            'plugins: ["./security/acme_rules.py"]',
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the file on disk is stale (for CI)",
    )
    args = parser.parse_args()

    content = render()
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != content:
            sys.stderr.write(
                "docs/RULES.md is out of date; run: python scripts/gen_rules_doc.py\n"
            )
            return 1
        return 0

    TARGET.write_text(content, encoding="utf-8")
    sys.stdout.write("wrote %s (%d rules)\n" % (TARGET, len(REGISTRY)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
